services:
  - type: web
    name: websocket-server
    env: python
    region: oregon  # Change based on your location
    plan: starter  # Or use "starter" for better performance
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 server.py"
    envVars:
      - key: PORT
        value: 443
